INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('Desarrollo web', 'Ing informatico', 'Bauxilum');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('Diseño de planos', 'Arquitecto', 'Venalum');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('ingles', 'almacenista', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('ingles', 'cajero', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('ingles', 'manejo al cambio', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('ingles', 'mensajero', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('ingles', 'recepcionista', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('ingles', 'supervisor', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('ingles', 'tester', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('ingles', 'tester', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de excel', 'almacenista', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de excel', 'cajero', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de excel', 'gerente', 'Panificadora Real');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de excel', 'gerente', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de excel', 'gerente', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de excel', 'manejo al cambio', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de excel', 'mensajero', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de excel', 'programador', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de excel', 'recepcionista', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de excel', 'supervisor', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de excel', 'UX/UI designer', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de powerpoint', 'almacenista', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de powerpoint', 'cajero', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de powerpoint', 'gerente', 'Panificadora Real');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de powerpoint', 'gerente', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de powerpoint', 'gerente', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de powerpoint', 'manejo al cambio', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de powerpoint', 'mensajero', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de powerpoint', 'programador', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de powerpoint', 'recepcionista', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de powerpoint', 'supervisor', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de powerpoint', 'UX/UI designer', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de word', 'almacenista', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de word', 'cajero', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de word', 'gerente', 'Panificadora Real');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de word', 'gerente', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de word', 'gerente', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de word', 'manejo al cambio', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de word', 'mensajero', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de word', 'programador', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de word', 'recepcionista', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de word', 'supervisor', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('manejo de word', 'UX/UI designer', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('toma de decisiones', 'almacenista', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('toma de decisiones', 'cajero', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('toma de decisiones', 'manejo al cambio', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('toma de decisiones', 'mensajero', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('toma de decisiones', 'programador', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('toma de decisiones', 'recepcionista', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('toma de decisiones', 'supervisor', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('toma de decisiones', 'UX/UI designer', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo bajo presion', 'almacenista', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo bajo presion', 'cajero', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo bajo presion', 'gerente', 'Panificadora Real');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo bajo presion', 'gerente', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo bajo presion', 'gerente', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo bajo presion', 'manejo al cambio', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo bajo presion', 'mensajero', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo bajo presion', 'programador', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo bajo presion', 'recepcionista', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo bajo presion', 'supervisor', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo bajo presion', 'tester', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo bajo presion', 'tester', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo bajo presion', 'UX/UI designer', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo en equipo', 'almacenista', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo en equipo', 'cajero', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo en equipo', 'gerente', 'Panificadora Real');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo en equipo', 'gerente', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo en equipo', 'gerente', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo en equipo', 'manejo al cambio', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo en equipo', 'mensajero', 'El artesano');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo en equipo', 'programador', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo en equipo', 'recepcionista', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo en equipo', 'supervisor', 'JL1290 CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo en equipo', 'tester', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo en equipo', 'tester', 'Palermo CA');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('trabajo en equipo', 'UX/UI designer', 'MyM San Félix');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('Uso de Excel', 'Administrador', 'Alcasa');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('Uso de Excel', 'Contador', 'Sidor');
INSERT INTO `consulta_1`(`Habilidad`, `Cargo_Disponible`, `Empresa`) VALUES ('Uso de Excel', 'Contador', 'Venalum');
