INSERT INTO `consulta_4`(`nombre_cargo`, `nombre`) VALUES ('Administrador', 'Alcasa');
INSERT INTO `consulta_4`(`nombre_cargo`, `nombre`) VALUES ('gerente', 'JL1290 CA');
INSERT INTO `consulta_4`(`nombre_cargo`, `nombre`) VALUES ('almacenista', 'JL1290 CA');
INSERT INTO `consulta_4`(`nombre_cargo`, `nombre`) VALUES ('recepcionista', 'JL1290 CA');
INSERT INTO `consulta_4`(`nombre_cargo`, `nombre`) VALUES ('mensajero', 'JL1290 CA');
INSERT INTO `consulta_4`(`nombre_cargo`, `nombre`) VALUES ('manejo al cambio', 'El artesano');
INSERT INTO `consulta_4`(`nombre_cargo`, `nombre`) VALUES ('mensajero', 'El artesano');
INSERT INTO `consulta_4`(`nombre_cargo`, `nombre`) VALUES ('UX/UI designer', 'MyM San Félix');
INSERT INTO `consulta_4`(`nombre_cargo`, `nombre`) VALUES ('Contador', 'Sidor');
INSERT INTO `consulta_4`(`nombre_cargo`, `nombre`) VALUES ('supervisor', 'Palermo CA');
INSERT INTO `consulta_4`(`nombre_cargo`, `nombre`) VALUES ('recepcionista', 'Palermo CA');
